#!/usr/bin/env python3
"""Create an app-owned relocatable runtime. Never copy recordings or research outputs."""
import json,subprocess,sys,os,shutil
from pathlib import Path
root=Path(__file__).resolve().parents[1]
target=root/'build/runtime'
def copy(source,dest):
    dest.parent.mkdir(parents=True,exist_ok=True)
    if not dest.exists():subprocess.run(['cp','-cR',str(source),str(dest)],check=True)
# Python is staged from python-build-standalone; no virtualenv absolute symlinks.
if not (target/'python/bin/python3').exists():
    raise SystemExit('Stage the portable Python runtime first; see docs/release/BUILD.md.')
for folder in ['server']:
    (target/folder).mkdir(parents=True,exist_ok=True)
    subprocess.run(['rsync','-a','--exclude=__pycache__',str(root/folder)+'/',str(target/folder)+'/'],check=True)
(target/'experiments').mkdir(exist_ok=True)
subprocess.run(['cp',str(root/'experiments/enhance_auk_local.py'),str(target/'experiments/enhance_auk_local.py')],check=True)
for name in ['source','models','SOURCE-LICENSE','requirements.lock']:
    copy(root/'.auk'/name,target/'.auk'/name)
(target/'.auk/READY.json').write_text(json.dumps({'format':1,'engine':'AuK','steps':32,'bits':8,'group_size':64}))
(target/'bin').mkdir(exist_ok=True)
ffmpeg=root/'build/ffmpeg-source/ffmpeg-7.1/ffmpeg'
if not ffmpeg.exists():raise SystemExit('Build the audio-only FFmpeg first; see docs/release/BUILD.md.')
subprocess.run(['cp',str(ffmpeg),str(target/'bin/ffmpeg')],check=True)
licenses=target/'licenses/ffmpeg'
licenses.mkdir(parents=True,exist_ok=True)
for name in ['COPYING.LGPLv2.1','LICENSE.md']:
    shutil.copy2(root/'build/ffmpeg-source/ffmpeg-7.1'/name,licenses/name)
shutil.copy2(root/'build/ffmpeg-source/ffmpeg-7.1.tar.xz',licenses/'ffmpeg-7.1-source.tar.xz')
shutil.copy2(root/'scripts/build-ffmpeg.sh',licenses/'build-ffmpeg.sh')
for name in ['config.log','config.mak']:
    (licenses/name).unlink(missing_ok=True)
(licenses/'README.txt').write_text('FFmpeg 7.1, LGPL 2.1 or later. Unmodified corresponding source and build script included. Invoked as a separate process. No GPL/nonfree modules. https://ffmpeg.org\n')
# FFmpeg is supplied by our audio-only LGPL build; discard an obsolete development fallback.
for obsolete in (target/'python/lib/python3.13/site-packages').iterdir():
    if not (obsolete.name.startswith('imageio_ffmpeg') or obsolete.name == 'av' or obsolete.name.startswith('av-')):continue
    if obsolete.is_dir():shutil.rmtree(obsolete)
# Strip generated bytecode to avoid developer absolute paths and stale imports.
for file in target.rglob('*.pyc'):file.unlink()
print(target)
