import {useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react'
import {PlayIcon,PauseIcon,DownloadIcon,CheckIcon} from '@radix-ui/react-icons'
import {Button} from '@/components/ui/button'
import {Switch} from '@/components/ui/switch'
import {audioUrl,clock,type Job} from './api'
import {native,invoke} from './native'
export function Player({job,disabled=false}:{job:Job,disabled?:boolean}){
 const [kind,setKind]=useState<'original'|'enhanced'>(job.enhanced?'enhanced':'original'),[playing,setPlaying]=useState(false),[time,setTime]=useState(0),[matched,setMatched]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false)
 const audio=useRef<HTMLAudioElement>(null),bar=useRef<HTMLDivElement>(null),pill=useRef<HTMLSpanElement>(null),mounted=useRef(false),desiredPlay=useRef(false),pendingTime=useRef(0),generation=useRef(0),saveLock=useRef(false)
 const state=useRef({kind,disabled,matched});state.current={kind,disabled,matched}
 const duration=job.original?.duration||0,peaks=useMemo(()=>(kind==='enhanced'?job.enhanced:job.original)?.peaks||[],[job.original,job.enhanced,kind]),max=Math.max(...peaks,.01)
 useLayoutEffect(()=>{function move(){const tab=bar.current?.querySelector<HTMLElement>('[aria-selected="true"]');if(!tab||!pill.current)return;const p=pill.current;if(!mounted.current)p.style.transition='none';p.style.transform=`translateX(${tab.offsetLeft}px)`;p.style.width=`${tab.offsetWidth}px`;void p.offsetWidth;p.style.transition='';mounted.current=true}move();const observer=new ResizeObserver(move);if(bar.current)observer.observe(bar.current);return()=>observer.disconnect()},[kind])
 useEffect(()=>{const a=audio.current;if(a){const gain=job.compare_gain||1;a.volume=matched?(kind==='original'?Math.min(1,gain):Math.min(1,1/gain)):1}},[matched,kind,job.compare_gain])
 useEffect(()=>()=>{generation.current++;desiredPlay.current=false;audio.current?.pause()},[])
 async function play(){const a=audio.current;if(!a)return;const id=generation.current;try{await a.play();if(id===generation.current&&!desiredPlay.current)a.pause()}catch(e){if(id===generation.current&&(e as DOMException).name!=='AbortError'){desiredPlay.current=false;setPlaying(false);setError('Playback failed. Try opening the recording again.')}}}
 function toggle(){const a=audio.current;if(!a)return;setError('');if(desiredPlay.current){desiredPlay.current=false;a.pause();setPlaying(false)}else{if(a.ended){a.currentTime=0;pendingTime.current=0}desiredPlay.current=true;if(a.readyState>=1)void play()}}
 function select(next:'original'|'enhanced'){if(next===state.current.kind||next==='enhanced'&&!job.enhanced)return;const a=audio.current;pendingTime.current=a?.currentTime||time;generation.current++;a?.pause();setPlaying(false);state.current.kind=next;setKind(next)}
 function seek(t:number){pendingTime.current=t;const a=audio.current;if(a&&a.readyState>=1)a.currentTime=t;setTime(t)}
 async function download(){if(saveLock.current||!job.enhanced)return;saveLock.current=true;setError('');setSaving(true);try{if(native){const didSave=await invoke<boolean>('export_audio',{jobId:job.id});if(didSave)setSaved(true)}else{const a=document.createElement('a');a.href=audioUrl(job,'enhanced')+'&download=true';a.download='';a.click();setSaved(true)}}catch{setError('Couldn’t save the file. Please try again.')}finally{saveLock.current=false;setSaving(false)}}
 const actions=useRef({toggle,select,download});actions.current={toggle,select,download}
 useEffect(()=>{const menu=(e:Event)=>{if(state.current.disabled)return;const id=(e as CustomEvent).detail;if(id==='play')actions.current.toggle();if(id==='compare')actions.current.select(state.current.kind==='original'?'enhanced':'original');if(id==='save')actions.current.download()};const key=(e:KeyboardEvent)=>{if(state.current.disabled||e.repeat)return;const target=e.target as HTMLElement;if(target.closest('input,textarea,button,[role="dialog"],[contenteditable="true"]'))return;if(e.code==='Space'){e.preventDefault();actions.current.toggle()}if(!native&&(e.metaKey||e.ctrlKey)&&e.key==='s'){e.preventDefault();actions.current.download()}};window.addEventListener('voicy-player',menu);window.addEventListener('keydown',key);return()=>{window.removeEventListener('voicy-player',menu);window.removeEventListener('keydown',key)}},[])
 return <div className="player"><div className="player-title"><h2 title={job.name}>{job.name}</h2></div>
 <div className="t-tabs" role="tablist" aria-label="Audio comparison" ref={bar}><span className="t-tabs-pill" ref={pill} aria-hidden="true"/>{(['original','enhanced'] as const).map(k=><button key={k} className="t-tab" role="tab" aria-selected={kind===k} tabIndex={kind===k?0:-1} disabled={k==='enhanced'&&!job.enhanced} onKeyDown={e=>{if(job.enhanced&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const next=k==='original'?'enhanced':'original';select(next);bar.current?.querySelectorAll<HTMLButtonElement>('button')[next==='original'?0:1].focus()}}} onClick={()=>select(k)}>{k==='original'?'Original':'Enhanced'}</button>)}</div>
 <div className="wave-wrap"><div className="waveform" aria-hidden="true">{peaks.map((p,i)=><i key={i} className={time>0&&i/peaks.length<=time/duration?'played':''} style={{height:`${Math.max(2,Math.sqrt(p/max)*100)}%`}}/>)}</div><input className="seek" type="range" min="0" max={duration} step=".1" value={time} aria-label="Playback position" aria-valuetext={`${clock(time)} of ${clock(duration)}`} onChange={e=>seek(+e.target.value)}/></div>
 <div className="transport"><span>{clock(time)}<span className="muted"> / {clock(duration)}</span></span><Button className="play-button" size="icon-lg" aria-label={playing?'Pause':'Play'} title="Play / Pause · Space" onClick={toggle}>{playing?<PauseIcon/>:<PlayIcon/>}</Button><span aria-hidden="true"/></div>
 {job.enhanced&&<div className="player-bottom"><label className="match"><Switch size="sm" checked={matched} onCheckedChange={setMatched} aria-label="Match playback volume"/><span>Match volume</span></label><Button size="sm" variant="ghost" disabled={saving} onClick={download} title="Export audio · ⌘S">{saved?<CheckIcon/>:<DownloadIcon/>}{saving?'Saving…':'Export'}</Button></div>}
 {error&&<p className="notice" role="alert">{error}</p>}
 <audio ref={audio} src={audioUrl(job,kind)} preload="metadata" onLoadedMetadata={e=>{const a=e.currentTarget;a.currentTime=Math.min(pendingTime.current,Math.max(0,(a.duration||duration)-.001));if(desiredPlay.current)void play()}} onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>{desiredPlay.current=false;setPlaying(false)}} onError={()=>{desiredPlay.current=false;setPlaying(false);setError('Couldn’t load this recording.')}}/></div>
}
