import {Sparkles,ArrowRight} from 'lucide-react'
import type {Settings as Options} from './api'
export function Settings({value,onChange,disabled,canRun,onRun,hasResult}:{value:Options;onChange:(s:Options)=>void;disabled:boolean;canRun:boolean;onRun:()=>void;hasResult:boolean}){
 const set=(patch:Partial<Options>)=>onChange({...value,...patch})
 return <aside className="settings"><h2>Make it sound like you</h2><p className="settings-intro">Clean up noise while keeping your natural voice.</p>
 <fieldset disabled={disabled}><legend className="sr-only">Enhancement settings</legend>
 <label className="field-label" htmlFor="engine">Audio engine</label><select id="engine" value={value.engine} onChange={e=>set({engine:e.target.value as Options['engine']})}><option value="denoise">Noise removal · fast</option><option value="mossformer">Full-band enhancement · MossFormer2</option><option value="studio">Studio restoration · experimental</option><option value="auk">AuK restoration · experimental</option><option value="restore">Voice restoration · experimental</option></select>
 {value.engine==='denoise'?<><span className="field-label">Enhancement type</span><div className="segments"><button aria-pressed={value.mode==='natural'} className={value.mode==='natural'?'selected':''} onClick={()=>set({mode:'natural'})}>Natural</button><button aria-pressed={value.mode==='strong'} className={value.mode==='strong'?'selected':''} onClick={()=>set({mode:'strong'})}>Strong</button></div><p className="help">{value.mode==='natural'?'Light, balanced noise removal for a natural sound.':'Deeper noise removal for challenging recordings.'}</p></>:value.engine==='auk'?<p className="help restore-note">Restores speech and reduces room echo locally. About 5 GB memory; several times slower than playback. May change vocal texture. Requires the optional AuK installation.</p>:value.engine==='studio'?<p className="help restore-note">Cleans the recording, then reconstructs speech detail. Slower and may alter vocal texture. Uses fixed model settings.</p>:value.engine==='mossformer'?<p className="help">Enhances speech across the full audio band. Uses the model’s fixed enhancement strength. Compare with your original.</p>:<p className="help restore-note">Reconstructs voice detail and reduces recording damage. Slower; may change vocal texture. Compare carefully.</p>}
 {!['mossformer','studio','auk'].includes(value.engine)&&<><label className="field-label amount-label" htmlFor="amount">{value.engine==='restore'?'Denoising before restoration':'Enhancement amount'} <span>{value.amount}%</span></label><input id="amount" type="range" min="0" max="100" value={value.amount} onChange={e=>set({amount:+e.target.value})} style={{background:`linear-gradient(to right,var(--accent) ${value.amount}%,var(--track) ${value.amount}%)`}}/><p className="help">{value.engine==='restore'?'Restoration remains active even at 0%.':'Higher values remove more noise.'}</p></>}
 <label className="toggle-row"><span><strong>Level volume</strong><small>Set a consistent listening level.</small></span><input type="checkbox" role="switch" checked={value.level} onChange={e=>set({level:e.target.checked})}/><span className="toggle" aria-hidden="true"/></label>
 </fieldset><button className="primary enhance" disabled={!canRun||disabled} onClick={onRun}><Sparkles size={19}/>{hasResult?'Enhance again':'Enhance speech'}<ArrowRight size={17}/></button><p className="button-help">{disabled?'Your Mac is working on it.':canRun?'Processed locally. No audio uploads.':'Add an audio file to get started.'}</p></aside>
}
